/* Auto generated file by build command shell.
    !!!!!!!! Do not edit this file. !!!!!!!!
    Created time : Tue May  7 00:49:33 KST 2013
    Created by chero@pantech.com (GS1 Team)
*/
#ifndef BOARD_REV_H
#define BOARD_REV_H

/*
Current MODEL ID is T_EF46L 
LINUX Kernel Define & macro function is as follows
#define CONFIG_MACH_MSM8960_EF46L
machine_is_msm8960_ef46l() function
*/

#define PT10  0x01
#define PT20  0x02
#define WS10  0x04
#define WS20  0x08
#define TP10  0x10
#define TP15  0x20
#define TP20  0x40
#define TP30  0x80

#define BOARD_VER   TP30
#endif /*BOARD_REV_H*/
